name: Archs

on: [push, pull_request]

jobs:
  build:

    # TODO: gcc crashes on ubuntu-latest/ubuntu24.04 with uraimo/run-on-arch-action
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: armv6
            distro: bookworm
          - arch: armv7
            distro: bookworm
          - arch: aarch64
            distro: bookworm
          - arch: riscv64
            # ubuntu22.04 / OpenSSL 3.0.2 seems to have an issue with EVP_PKEY_fromdata(EVP_PKEY_KEYPAIR)
            distro: ubuntu_latest
          - arch: s390x
            distro: bookworm
          - arch: ppc64le
            distro: bookworm

    steps:
    - uses: actions/checkout@v4
    - uses: uraimo/run-on-arch-action@v2
      name: Build
      id: build
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        env: |
          CK_MAX_MSG_SIZE: 40960
          logfilename: test-suite-${{ matrix.distro }}-${{ matrix.arch }}.log
        install: |
          apt-get update -y
          apt-get install -y pkg-config make gdb autoconf automake libtool
          apt-get install -y libssl-dev libjansson-dev check
        setup: |
          mkdir -p "${PWD}/logs"
        dockerRunArgs: |
          --volume "${PWD}/logs:/logs"
        run: |
          touch aclocal.m4 configure Makefile.am Makefile.in
          ./configure --with-rsapkcs1_5 || cat config.log
          make check || { cat test/test-suite.log && (exit -1) }
          cat test/*.log >> "/logs/${logfilename}"
          echo "Copied test logs to /logs/${logfilename}"
    - name: Results
      run: |
        cat ${PWD}/logs/*.log
