name: Archs

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu20.04
          - arch: aarch64
            distro: ubuntu20.04
          - arch: ppc64le
            distro: ubuntu20.04
          - arch: s390x
            distro: ubuntu20.04
  
    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      name: Build
      id: build
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        install: |
          apt-get update -y
          apt-get install -y pkg-config make gcc gdb valgrind vim autoconf automake libtool
          apt-get install -y libssl-dev libjansson-dev check
        setup: |
          mkdir -p "${PWD}/logs"
        dockerRunArgs: |
          --volume "${PWD}/logs:/logs"
        env: |
          logfilename: test-suite-${{ matrix.distro }}-${{ matrix.arch }}.log
        run: |
          touch aclocal.m4 configure Makefile.am Makefile.in
          ./configure CFLAGS="-g -O0" LDFLAGS="-lrt"
          make check
          cat test/*.log >> "/logs/${logfilename}"
          echo "Copied test logs to /logs/${logfilename}"
          
    - name: Results
      run: |
        cat ${PWD}/logs/*.log
