name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config make gcc valgrind autoconf automake libtool
        sudo apt-get install -y libssl-dev libjansson-dev check
    - name: Configure
      run: |
          touch aclocal.m4 configure Makefile.am Makefile.in
          ./configure --with-rsapkcs1_5  || { cat config.log && (exit -1) }
    - name: Make
      run: make
    - name: Test
      run: make check || { cat test/test-suite.log && (exit -1) }
    - name: Valgrind
      env:
        CK_FORK: no
      run: |
        valgrind --leak-check=full --error-exitcode=1 --show-possibly-lost=no --read-inline-info=yes --keep-debuginfo=yes --undef-value-errors=no ./test/check_cjose
