name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config make gcc gdb valgrind vim autoconf automake libtool
        sudo apt-get install -y libssl-dev libjansson-dev check
    - name: Configure
      run: |
        touch aclocal.m4 configure Makefile.am Makefile.in 
        ./configure
    - name: Make
      run: make
    - name: Test
      run: make check
    - name: Valgrind
      run: |
        CK_FORK=no valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=definite --read-inline-info=yes --keep-debuginfo=yes --undef-value-errors=no ./test/check_cjose
